services:
  - type: web
    name: nutrition-tracker-nodejs
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://<user>:<password>@cluster0.example.mongodb.net/?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production
    github:
      repo: siddh2510/NutritionTracker
      branch: main
