services:
  - type: static_site
    name: nutrition-tracker
    env: static
    buildCommand: ''
    publishDirectory: '.'  # Points to the root directory
    staticPublishPath: '/'
    github:
      repo: 'siddh2510/NutritionTracker'
    branch: 'main'
