services:
  - type: web
    name: nutrition-tracker-nodejs
    env: node
    buildCommand: npm install && npm run build  # optional if no build step
    startCommand: npm start
    github:
      repo: siddh2510/NutritionTracker
      branch: main
